# Generated by Django 6.0.7 on 2026-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('package', models.DecimalField(decimal_places=2, max_digits=8)),
                ('placement_date', models.DateField()),
                ('company_logo', models.ImageField(upload_to='placements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
