# Generated by Django 6.0.7 on 2026-08-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_created_at_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fee',
            new_name='fees',
        ),
    ]
