# Generated by Django 6.0.7 on 2026-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='experience',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='instructors/'),
            preserve_default=False,
        ),
    ]
